services:
  php:
    container_name: docker_php
    build: .docker/php
    volumes:
      - .:/home/wwwroot
    ports:
      - '8000:8000'
    command: php -S 0.0.0.0:8000 -t /home/wwwroot/04_Iteration_4_Passage_a_l_Echelle/formulaire_recherche_sirene

  db:
    build: .docker/db
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    container_name: docker_mysql
    restart: always
    ports:
      - '6603:3306'

  spring-spark-dashboard:
    container_name: docker_spring_spark_dashboard
    image: maven:3.9.6-eclipse-temurin-17
    volumes:
      - .:/home/wwwroot
    ports:
      - '8090:8090'
    working_dir: /home/wwwroot/05_Iteration_5_SQL_Analytique_et_Spark/spring_spark_dashboard
    command: mvn spring-boot:run
